2014-05-09 22:57:37,438 INFO: povodochek startup [in app.py:293]
2014-05-09 23:22:22,261 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:22:46,522 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:23:22,105 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:29:22,964 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:30:22,200 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:34:43,257 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:38:35,215 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:41:55,710 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:42:33,867 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:43:10,495 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:44:14,701 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    @app.errorhandler(404)
NameError: global name 's' is not defined
2014-05-09 23:44:48,602 INFO: povodochek startup [in app.py:293]
2014-05-09 23:44:51,510 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:55:50,886 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    def tos():
NameError: global name 's' is not defined
2014-05-09 23:57:59,956 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:58:19,475 INFO: povodochek startup [in app.py:293]
2014-05-09 23:58:40,931 ERROR: Exception on /tos/ [GET] [in /home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py:1306]
Traceback (most recent call last):
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egor/povodochek/venv/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 1285, in tos
    print(s.sdfh)
NameError: global name 's' is not defined
2014-05-09 23:58:41,106 WARNING: <JKHSKJHASDJ:LSJD:SAJ [in app.py:1299]
